### ISSUE TITLE
使用Python 3.7.2运行时出错

### ISSUE THREAD

**Issue by GlassesFrog** [yinghualuowu/Python_VLPR#2]
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Python37\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "C:\Users\18167\Desktop\Python_VLPR-master\main_VLPR.py", line 26, in run
    self._return1, self._return2, self._return3 = self._target(*self._args, **self._kwargs)
  File "C:\Users\18167\Desktop\Python_VLPR-master\img_function.py", line 157, in img_color_contours
    card_contours = img_math.img_findContours(img_contours)
  File "C:\Users\18167\Desktop\Python_VLPR-master\img_math.py", line 88, in img_findContours
    img, contours, hierarchy = cv2.findContours(img_contours, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
ValueError: not enough values to unpack (expected 3, got 2)

Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\Python37\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "C:\Users\18167\Desktop\Python_VLPR-master\main_VLPR.py", line 26, in run
    self._return1, self._return2, self._return3 = self._target(*self._args, **self._kwargs)
  File "C:\Users\18167\Desktop\Python_VLPR-master\img_function.py", line 280, in img_only_color
    card_contours = img_math.img_findContours(img_edge2)
  File "C:\Users\18167\Desktop\Python_VLPR-master\img_math.py", line 88, in img_findContours
    img, contours, hierarchy = cv2.findContours(img_contours, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
ValueError: not enough values to unpack (expected 3, got 2)

None None

**Comment by yinghualuowu** [comment]
已经解决~
